import { Destination } from '@/types/domain'

// Every hero image URL below was individually verified (HTTP 200 via curl)
// before being added here — several of the ones originally in this file had
// gone dead (Unsplash photo IDs get removed over time), which silently broke
// destination cards. See TravelCard.tsx for the runtime fallback that covers
// any future rot; this file just starts from a known-good set.
export const FEATURED_DESTINATIONS: Destination[] = [
  // ---------------------------------------------------------------- EUROPA
  {
    id: 'paris',
    name: 'Paris',
    country: 'Francia',
    region: 'Île-de-France',
    timezone: 'Europe/Paris',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    description: 'La Ciudad de Luz. Romance, arte y cocina de primer nivel.',
    images: {
      hero: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 12, rainfall: 640, bestMonths: ['Abril', 'Mayo', 'Septiembre', 'Octubre'] },
    travelScore: 95,
    difficulty: 'easy',
    currency: 'EUR',
    languages: ['Francés', 'Inglés'],
    attractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Arc de Triomphe'],
    safetyRating: 8.5,
    costOfLiving: 'expensive',
    accessibility: ['Transporte público', 'Museos', 'Restaurantes'],
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'España',
    region: 'Cataluña',
    timezone: 'Europe/Madrid',
    coordinates: { lat: 41.3874, lng: 2.1900 },
    description: 'Arquitectura de Gaudí, playa mediterránea y energía joven todo el año.',
    images: {
      hero: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 18, rainfall: 580, bestMonths: ['Mayo', 'Junio', 'Septiembre'] },
    travelScore: 94,
    difficulty: 'easy',
    currency: 'EUR',
    languages: ['Español', 'Catalán', 'Inglés'],
    attractions: ['Sagrada Familia', 'Park Güell', 'Las Ramblas', 'Barceloneta Beach'],
    safetyRating: 8,
    costOfLiving: 'moderate',
    accessibility: ['Transporte público', 'Playas', 'Vida nocturna'],
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Países Bajos',
    region: 'Holanda del Norte',
    timezone: 'Europe/Amsterdam',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    description: 'Canales, bicicletas y un encanto relajado que atrapa a cualquier edad.',
    images: {
      hero: 'https://images.unsplash.com/photo-1576924542622-772281b13aa8?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 10, rainfall: 780, bestMonths: ['Abril', 'Mayo', 'Junio', 'Septiembre'] },
    travelScore: 90,
    difficulty: 'easy',
    currency: 'EUR',
    languages: ['Neerlandés', 'Inglés'],
    attractions: ['Canales', 'Rijksmuseum', 'Anne Frank House', 'Vondelpark'],
    safetyRating: 8.7,
    costOfLiving: 'expensive',
    accessibility: ['Bicicletas', 'Transporte público', 'Museos'],
  },
  {
    id: 'roma',
    name: 'Roma',
    country: 'Italia',
    region: 'Lacio',
    timezone: 'Europe/Rome',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    description: 'Historia viva en cada esquina, pasta imbatible y atardeceres épicos.',
    images: {
      hero: 'https://images.unsplash.com/photo-1523652615028-87da4d4427b7?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 16, rainfall: 660, bestMonths: ['Abril', 'Mayo', 'Septiembre', 'Octubre'] },
    travelScore: 93,
    difficulty: 'easy',
    currency: 'EUR',
    languages: ['Italiano', 'Inglés'],
    attractions: ['Coliseo', 'Vaticano', 'Fontana di Trevi', 'Foro Romano'],
    safetyRating: 7.8,
    costOfLiving: 'moderate',
    accessibility: ['Transporte público', 'Sitios históricos', 'Restaurantes'],
  },
  {
    id: 'londres',
    name: 'Londres',
    country: 'Reino Unido',
    region: 'Inglaterra',
    timezone: 'Europe/London',
    coordinates: { lat: 51.5072, lng: -0.1276 },
    description: 'Ícono global, museos gratis y una escena musical que nunca duerme.',
    images: {
      hero: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 11, rainfall: 600, bestMonths: ['Mayo', 'Junio', 'Julio', 'Septiembre'] },
    travelScore: 91,
    difficulty: 'easy',
    currency: 'GBP',
    languages: ['Inglés'],
    attractions: ['Big Ben', 'Tower Bridge', 'British Museum', 'Camden Market'],
    safetyRating: 8.2,
    costOfLiving: 'expensive',
    accessibility: ['Transporte público', 'Museos gratuitos', 'Vida nocturna'],
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Grecia',
    region: 'Cícladas',
    timezone: 'Europe/Athens',
    coordinates: { lat: 36.4169, lng: 25.4615 },
    description: 'Atardeceres imposibles, casas blancas y azules sobre el mar Egeo.',
    images: {
      hero: 'https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 25, rainfall: 400, bestMonths: ['Abril', 'Mayo', 'Septiembre', 'Octubre'] },
    travelScore: 94,
    difficulty: 'easy',
    currency: 'EUR',
    languages: ['Griego', 'Inglés'],
    attractions: ['Oia', 'Caldera', 'Playas volcánicas', 'Catas de vino'],
    safetyRating: 9,
    costOfLiving: 'expensive',
    accessibility: ['Restaurantes', 'Playas', 'Vistas panorámicas'],
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'España',
    region: 'Comunidad de Madrid',
    timezone: 'Europe/Madrid',
    coordinates: { lat: 40.4168, lng: -3.7038 },
    description: 'Tapas, terrazas y una vida nocturna que empieza cuando el resto duerme.',
    images: {
      hero: 'https://images.unsplash.com/photo-1763635501946-4a599e293fb3?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 15, rainfall: 420, bestMonths: ['Abril', 'Mayo', 'Septiembre', 'Octubre'] },
    travelScore: 90,
    difficulty: 'easy',
    currency: 'EUR',
    languages: ['Español'],
    attractions: ['Plaza Mayor', 'Museo del Prado', 'Retiro Park', 'Gran Vía'],
    safetyRating: 8.3,
    costOfLiving: 'moderate',
    accessibility: ['Transporte público', 'Vida nocturna', 'Gastronomía'],
  },

  // -------------------------------------------------------------- AMÉRICA
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    region: 'Buenos Aires',
    timezone: 'America/Argentina/Buenos_Aires',
    coordinates: { lat: -34.6037, lng: -58.3816 },
    description: 'Tango, asado y una elegancia europea con acento porteño.',
    images: {
      hero: 'https://images.unsplash.com/photo-1764066531610-5457f1bc5419?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 18, rainfall: 1200, bestMonths: ['Marzo', 'Abril', 'Octubre', 'Noviembre'] },
    travelScore: 89,
    difficulty: 'easy',
    currency: 'ARS',
    languages: ['Español'],
    attractions: ['Teatro Colón', 'La Boca', 'Recoleta', 'Puerto Madero'],
    safetyRating: 6.8,
    costOfLiving: 'cheap',
    accessibility: ['Transporte público', 'Vida nocturna', 'Gastronomía'],
  },
  {
    id: 'cartagena',
    name: 'Cartagena',
    country: 'Colombia',
    region: 'Bolívar',
    timezone: 'America/Bogota',
    coordinates: { lat: 10.3932, lng: -75.4898 },
    description: 'Arquitectura colonial colorida y encanto caribeño frente al mar.',
    images: {
      hero: 'https://images.unsplash.com/photo-1560242374-ca6dd3434522?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 27, rainfall: 1500, bestMonths: ['Diciembre', 'Enero', 'Febrero'] },
    travelScore: 89,
    difficulty: 'easy',
    currency: 'COP',
    languages: ['Español'],
    attractions: ['Ciudad Amurallada', 'Islas del Rosario', 'Castillo San Felipe', 'Playas'],
    safetyRating: 7,
    costOfLiving: 'cheap',
    accessibility: ['Restaurantes', 'Playas', 'Sitios históricos'],
  },
  {
    id: 'mexico-city',
    name: 'Ciudad de México',
    country: 'México',
    region: 'CDMX',
    timezone: 'America/Mexico_City',
    coordinates: { lat: 19.4326, lng: -99.1332 },
    description: 'Capital vibrante con cultura prehispánica, arte y gastronomía de primer nivel.',
    images: {
      hero: 'https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 17, rainfall: 800, bestMonths: ['Octubre', 'Noviembre', 'Marzo', 'Abril'] },
    travelScore: 92,
    difficulty: 'moderate',
    currency: 'MXN',
    languages: ['Español'],
    attractions: ['Zócalo', 'Museo Frida Kahlo', 'Chapultepec', 'Xochimilco'],
    safetyRating: 6.5,
    costOfLiving: 'cheap',
    accessibility: ['Transporte público', 'Museos', 'Gastronomía'],
  },
  {
    id: 'cancun',
    name: 'Cancún',
    country: 'México',
    region: 'Quintana Roo',
    timezone: 'America/Cancun',
    coordinates: { lat: 21.1619, lng: -86.8515 },
    description: 'Playas turquesas, cenotes mágicos y la mejor fiesta de la Riviera Maya.',
    images: {
      hero: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 27, rainfall: 1100, bestMonths: ['Mayo', 'Junio', 'Octubre', 'Noviembre'] },
    travelScore: 87,
    difficulty: 'easy',
    currency: 'MXN',
    languages: ['Español', 'Inglés'],
    attractions: ['Playa Delfines', 'Isla Mujeres', 'Cenotes', 'Ruinas de Tulum'],
    safetyRating: 7.2,
    costOfLiving: 'moderate',
    accessibility: ['Playas', 'Resorts', 'Vida nocturna'],
  },
  {
    id: 'cusco',
    name: 'Cusco',
    country: 'Perú',
    region: 'Cusco',
    timezone: 'America/Lima',
    coordinates: { lat: -13.5319, lng: -71.9675 },
    description: 'Puerta de entrada a Machu Picchu, historia inca y montañas imponentes.',
    images: {
      hero: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 12, rainfall: 700, bestMonths: ['Mayo', 'Junio', 'Julio', 'Agosto'] },
    travelScore: 92,
    difficulty: 'challenging',
    currency: 'PEN',
    languages: ['Español', 'Quechua'],
    attractions: ['Machu Picchu', 'Valle Sagrado', 'Plaza de Armas', 'Sacsayhuamán'],
    safetyRating: 7.5,
    costOfLiving: 'cheap',
    accessibility: ['Trekking', 'Sitios históricos', 'Altura elevada'],
  },
  {
    id: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    country: 'Brasil',
    region: 'Rio de Janeiro',
    timezone: 'America/Sao_Paulo',
    coordinates: { lat: -22.9068, lng: -43.1729 },
    description: 'Playas icónicas, Cristo Redentor y una energía que se siente en cada esquina.',
    images: {
      hero: 'https://images.unsplash.com/photo-1763110805416-22e7a6fffa58?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 24, rainfall: 1200, bestMonths: ['Abril', 'Mayo', 'Septiembre', 'Octubre'] },
    travelScore: 90,
    difficulty: 'moderate',
    currency: 'BRL',
    languages: ['Portugués'],
    attractions: ['Cristo Redentor', 'Copacabana', 'Pan de Azúcar', 'Ipanema'],
    safetyRating: 6,
    costOfLiving: 'moderate',
    accessibility: ['Playas', 'Vida nocturna', 'Naturaleza'],
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    region: 'Cundinamarca',
    timezone: 'America/Bogota',
    coordinates: { lat: 4.7110, lng: -74.0721 },
    description: 'Arte urbano, café de altura y montañas que enmarcan toda la ciudad.',
    images: {
      hero: 'https://images.unsplash.com/photo-1633624465404-166b904af53d?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 14, rainfall: 1000, bestMonths: ['Diciembre', 'Enero', 'Febrero'] },
    travelScore: 86,
    difficulty: 'easy',
    currency: 'COP',
    languages: ['Español'],
    attractions: ['Monserrate', 'La Candelaria', 'Museo del Oro', 'Zona Rosa'],
    safetyRating: 6.5,
    costOfLiving: 'cheap',
    accessibility: ['Transporte público', 'Arte urbano', 'Gastronomía'],
  },

  // ----------------------------------------------------------------- ASIA
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japón',
    region: 'Kanto',
    timezone: 'Asia/Tokyo',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    description: 'Templos antiguos se encuentran con tecnología de vanguardia. Fascinante.',
    images: {
      hero: 'https://images.unsplash.com/photo-1741920852881-5284c70305bd?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 15, rainfall: 1500, bestMonths: ['Marzo', 'Abril', 'Octubre', 'Noviembre'] },
    travelScore: 93,
    difficulty: 'moderate',
    currency: 'JPY',
    languages: ['Japonés', 'Inglés (limitado)'],
    attractions: ['Shibuya Crossing', 'Senso-ji Temple', 'Tokyo Tower', 'teamLab'],
    safetyRating: 9.5,
    costOfLiving: 'moderate',
    accessibility: ['Transporte público', 'Restaurantes', 'Sitios culturales'],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Bali',
    timezone: 'Asia/Makassar',
    coordinates: { lat: -8.6705, lng: 115.2126 },
    description: 'Playas paradisíacas, templos espirituales y arrozales verdes.',
    images: {
      hero: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 28, rainfall: 3000, bestMonths: ['Abril', 'Mayo', 'Junio', 'Septiembre'] },
    travelScore: 91,
    difficulty: 'easy',
    currency: 'IDR',
    languages: ['Indonesio', 'Inglés'],
    attractions: ['Ubud', 'Tanah Lot', 'Seminyak Beach', 'Mount Batur'],
    safetyRating: 7.5,
    costOfLiving: 'cheap',
    accessibility: ['Restaurantes', 'Playas', 'Sitios culturales'],
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Tailandia',
    region: 'Bangkok',
    timezone: 'Asia/Bangkok',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    description: 'Templos dorados, mercados caóticos y street food que se come a cualquier hora.',
    images: {
      hero: 'https://images.unsplash.com/photo-1750635410058-b77811c3c01f?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 29, rainfall: 1500, bestMonths: ['Noviembre', 'Diciembre', 'Enero', 'Febrero'] },
    travelScore: 90,
    difficulty: 'easy',
    currency: 'THB',
    languages: ['Tailandés', 'Inglés'],
    attractions: ['Gran Palacio', 'Wat Arun', 'Mercado flotante', 'Khao San Road'],
    safetyRating: 7,
    costOfLiving: 'cheap',
    accessibility: ['Transporte público', 'Vida nocturna', 'Street food'],
  },
  {
    id: 'phuket',
    name: 'Phuket',
    country: 'Tailandia',
    region: 'Phuket',
    timezone: 'Asia/Bangkok',
    coordinates: { lat: 7.8804, lng: 98.3923 },
    description: 'Playas blancas, islas cercanas y un ambiente tropical de puro relax.',
    images: {
      hero: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 28, rainfall: 2200, bestMonths: ['Noviembre', 'Diciembre', 'Enero', 'Febrero'] },
    travelScore: 87,
    difficulty: 'easy',
    currency: 'THB',
    languages: ['Tailandés', 'Inglés'],
    attractions: ['Patong Beach', 'Phi Phi Islands', 'Big Buddha', 'Old Town'],
    safetyRating: 7.3,
    costOfLiving: 'cheap',
    accessibility: ['Playas', 'Islas', 'Vida nocturna'],
  },
  {
    id: 'singapur',
    name: 'Singapur',
    country: 'Singapur',
    region: 'Singapur',
    timezone: 'Asia/Singapore',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    description: 'Rascacielos futuristas, gastronomía de clase mundial y una eficiencia impecable.',
    images: {
      hero: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 27, rainfall: 2300, bestMonths: ['Febrero', 'Marzo', 'Abril'] },
    travelScore: 89,
    difficulty: 'easy',
    currency: 'SGD',
    languages: ['Inglés', 'Mandarín', 'Malayo'],
    attractions: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa', 'Chinatown'],
    safetyRating: 9.5,
    costOfLiving: 'expensive',
    accessibility: ['Transporte público', 'Gastronomía', 'Modernidad'],
  },

  // --------------------------------------------------------------- ÁFRICA
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Marruecos',
    region: 'Marrakech-Safi',
    timezone: 'Africa/Casablanca',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    description: 'Zocos, colores y una medina que parece sacada de otro tiempo.',
    images: {
      hero: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 20, rainfall: 250, bestMonths: ['Marzo', 'Abril', 'Octubre', 'Noviembre'] },
    travelScore: 86,
    difficulty: 'moderate',
    currency: 'MAD',
    languages: ['Árabe', 'Francés'],
    attractions: ['Medina', 'Jemaa el-Fnaa', 'Jardín Majorelle', 'Zocos'],
    safetyRating: 7,
    costOfLiving: 'cheap',
    accessibility: ['Mercados', 'Sitios históricos', 'Gastronomía'],
  },
  {
    id: 'cape-town',
    name: 'Ciudad del Cabo',
    country: 'Sudáfrica',
    region: 'Western Cape',
    timezone: 'Africa/Johannesburg',
    coordinates: { lat: -33.9249, lng: 18.4241 },
    description: 'Montaña, mar y aventura en una de las ciudades más espectaculares del mundo.',
    images: {
      hero: 'https://images.unsplash.com/photo-1744604030401-b24c5975a574?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 17, rainfall: 500, bestMonths: ['Noviembre', 'Diciembre', 'Marzo', 'Abril'] },
    travelScore: 88,
    difficulty: 'moderate',
    currency: 'ZAR',
    languages: ['Inglés', 'Afrikáans', 'Xhosa'],
    attractions: ['Table Mountain', 'Cape of Good Hope', 'V&A Waterfront', 'Robben Island'],
    safetyRating: 6.3,
    costOfLiving: 'cheap',
    accessibility: ['Naturaleza', 'Playas', 'Vida silvestre'],
  },
  {
    id: 'egipto',
    name: 'Giza',
    country: 'Egipto',
    region: 'El Cairo',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 29.9773, lng: 31.1325 },
    description: 'Las pirámides más famosas del planeta y miles de años de historia.',
    images: {
      hero: 'https://images.unsplash.com/photo-1710069441986-82759c8a200c?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 22, rainfall: 25, bestMonths: ['Octubre', 'Noviembre', 'Marzo', 'Abril'] },
    travelScore: 85,
    difficulty: 'moderate',
    currency: 'EGP',
    languages: ['Árabe', 'Inglés'],
    attractions: ['Pirámides de Giza', 'Esfinge', 'Museo Egipcio', 'Río Nilo'],
    safetyRating: 6.8,
    costOfLiving: 'cheap',
    accessibility: ['Sitios históricos', 'Tours guiados'],
  },

  // ------------------------------------------------------------- OCEANÍA
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'Nueva Gales del Sur',
    timezone: 'Australia/Sydney',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    description: 'Ópera icónica, playas urbanas y una calidad de vida difícil de igualar.',
    images: {
      hero: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 18, rainfall: 1200, bestMonths: ['Septiembre', 'Octubre', 'Marzo', 'Abril'] },
    travelScore: 91,
    difficulty: 'easy',
    currency: 'AUD',
    languages: ['Inglés'],
    attractions: ['Opera House', 'Harbour Bridge', 'Bondi Beach', 'Darling Harbour'],
    safetyRating: 9,
    costOfLiving: 'expensive',
    accessibility: ['Playas', 'Transporte público', 'Vida nocturna'],
  },
  {
    id: 'nueva-zelanda',
    name: 'Queenstown',
    country: 'Nueva Zelanda',
    region: 'Otago',
    timezone: 'Pacific/Auckland',
    coordinates: { lat: -45.0312, lng: 168.6626 },
    description: 'Naturaleza pura, montañas y la capital mundial del deporte de aventura.',
    images: {
      hero: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
      gallery: [],
    },
    climate: { avgTemp: 11, rainfall: 900, bestMonths: ['Diciembre', 'Enero', 'Febrero', 'Marzo'] },
    travelScore: 92,
    difficulty: 'moderate',
    currency: 'NZD',
    languages: ['Inglés', 'Maorí'],
    attractions: ['Lake Wakatipu', 'Milford Sound', 'Deportes extremos', 'Fiordland'],
    safetyRating: 9.3,
    costOfLiving: 'expensive',
    accessibility: ['Naturaleza', 'Trekking', 'Deportes de aventura'],
  },
]

export const TRAVEL_INTERESTS = [
  { id: 'beach', label: 'Beach & Relax', icon: '🏖️' },
  { id: 'adventure', label: 'Adventure', icon: '🧗' },
  { id: 'romantic', label: 'Romantic', icon: '💑' },
  { id: 'family', label: 'Family', icon: '👨‍👩‍👧‍👦' },
  { id: 'culture', label: 'Culture', icon: '🏛️' },
  { id: 'luxury', label: 'Luxury', icon: '✨' },
  { id: 'nature', label: 'Nature', icon: '🌲' },
  { id: 'escape', label: 'Escape', icon: '🌅' },
] as const
